//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcodexWebSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AcodexWeb_DbEntities : DbContext
    {
        public AcodexWeb_DbEntities()
            : base("name=AcodexWeb_DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblDocumention> TblDocumention { get; set; }
        public virtual DbSet<TblFilm> TblFilm { get; set; }
        public virtual DbSet<TblProjects> TblProjects { get; set; }
        public virtual DbSet<TblRoadMaps> TblRoadMaps { get; set; }
        public virtual DbSet<TblShop> TblShop { get; set; }
        public virtual DbSet<TblSource> TblSource { get; set; }
    }
}
